services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-linkly}
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --loglevel debug

  # Add this service to monitor Redis
  redis-monitor:
    image: redis:7-alpine
    depends_on:
      - redis
    command: redis-cli -h redis MONITOR

volumes:
  postgres_data:
  redis_data: