services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --loglevel debug

  # Add this service to monitor Redis
  redis-monitor:
    image: redis:7-alpine
    depends_on:
      - redis
    command: redis-cli -h redis MONITOR

volumes:
  postgres_data:
  redis_data: