services:
  test:
    build:
      context: .
      dockerfile: app/Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/linkly_test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEST_MODE=True
      - SECRET_KEY=test-secret-key-for-testing-only-not-for-production
      - DEBUG=true
      - ENVIRONMENT=test

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=linkly_test
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --loglevel warning
